version: 2
jobs:
  build:
    working_directory: ~/catarse/catarse.js
    parallelism: 1
    shell: /bin/bash --login
    environment:
      CIRCLE_ARTIFACTS: /tmp/circleci-artifacts
      CIRCLE_TEST_REPORTS: /tmp/circleci-test-results
    docker:
      - image: circleci/node:12.18.3-browsers
    steps:
      - checkout
      - run: mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS
      - run:
          working_directory: ~/catarse/catarse.js
          command: |
            set -ex \
            && mkdir -p $CIRCLE_ARTIFACTS $CIRCLE_TEST_REPORTS \
            && cd services/catarse.js
      - restore_cache:
          keys:
            - v1-dep-{{ .Branch }}-
      - run: if [ -z "${NODE_ENV:-}" ]; then export NODE_ENV=test; fi
      - run: export PATH="~/catarse/catarse.js/node_modules/.bin:$PATH"
      - run: npm install
      - save_cache:
          key: v1-dep-{{ .Branch }}-{{ epoch }}
          paths:
            # This is a broad list of cache paths to include many possible development environments
            # You can probably delete some of these entries
            - ./node_modules
      - run: npm test
      - store_test_results:
          path: /tmp/circleci-test-results
      # Save artifacts
      - store_artifacts:
          path: /tmp/circleci-artifacts
      - store_artifacts:
          path: /tmp/circleci-test-results
